### ISSUE TITLE
Well, this is awkward

### ISSUE THREAD

**Issue by Tyfyter** [GoldenRound/Entropy-Tmod#1]
One of us will have to change our mod's name, or we could merge our mods.

**Comment by GoldenRound** [comment]
Lol, nope

**Comment by Tyfyter** [comment]
I guess great minds think alike?

**Comment by Tyfyter** [comment]
https://drive.google.com/open?id=1WCzQyhsNZ3Tz3tpUGgZ96QDl8_XIt6so
